// Three Degrees Salon — Real Business Data
// Collected from official website, Google, Yelp, Instagram

export const BUSINESS = {
  name: "Three Degrees Salon",
  tagline: "Where Your Hair Finds Its Style",
  tagline2: "Japanese Concept Hair Salon in East Village, NYC",
  address: "204 E 6th Street, New York, NY 10003",
  neighborhood: "East Village",
  phone: "(212) 254-8174",
  email: "info@threedegreesnyc.com",
  website: "https://threedegreesnyc.com",
  booking: "https://threedegreesnyc.com/appointment/",
  instagram: "https://www.instagram.com/threedegreessalon/",
  facebook: "https://www.facebook.com/485333182233409",
  googleMaps: "https://maps.google.com/?cid=1896903633712263589",
  rating: 4.9,
  reviewCount: 384,
  googleReviewCount: 214,
  founded: 2019,
  hours: {
    monday: "9:00 AM – 7:00 PM",
    tuesday: "9:00 AM – 7:00 PM",
    wednesday: "9:00 AM – 7:00 PM",
    thursday: "9:00 AM – 7:00 PM",
    friday: "9:00 AM – 7:00 PM",
    saturday: "9:00 AM – 7:00 PM",
    sunday: "9:00 AM – 7:00 PM",
  },
  hoursDisplay: "Mon – Sun: 9:00 AM – 7:00 PM",
  amenities: [
    "Wheelchair Entrance",
    "Wheelchair Seating",
    "Gender-Neutral Restroom",
    "Free WiFi",
    "Appointments Recommended",
    "Walk-ins Accepted",
    "Credit Cards",
    "Debit Cards",
    "NFC Payments",
    "Complimentary Beverages",
    "Plastic Recycling",
  ],
  awards: [
    { title: "Best Salon in NYC", source: "Hairdressr.com", year: "2023" },
    { title: "Top Hair Salon", source: "Best Pros In Town", year: "2023" },
    { title: "Featured Salon", source: "Hair.com", year: "2024" },
    { title: "Featured", source: "Refinery29", year: "2021" },
    { title: "Featured", source: "Fox34 News", year: "2023" },
    { title: "Featured", source: "ABC6 News", year: "2023" },
    { title: "Featured", source: "Shukan New York Seikatsu", year: "2021" },
  ],
  press: [
    { name: "Hair.com", url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/IMG_1136.jpg" },
    { name: "Hairdressr.com", url: "https://threedegreesnyc.com/wp-content/uploads/2023/11/hairdressr.com_.jpg" },
    { name: "Refinery29", url: "https://threedegreesnyc.com/wp-content/uploads/2021/11/Refinery2B292Bweb2Bscreen2Bshot.jpg" },
    { name: "Fox34 News", url: "https://threedegreesnyc.com/wp-content/uploads/2023/07/Fox34.com-screen-shot.jpg" },
    { name: "ABC6 News", url: "https://threedegreesnyc.com/wp-content/uploads/2023/07/abc6-news-screenshot.jpg" },
  ],
};

export const STATS = [
  { number: 384, suffix: "+", label: "5-Star Reviews" },
  { number: 4.9, suffix: "★", label: "Average Rating", decimal: true },
  { number: 2019, suffix: "", label: "Est. in NYC" },
  { number: 7, suffix: "", label: "Expert Stylists" },
];

export const STYLISTS = [
  {
    id: "kei-hirata",
    name: "Kei Hirata",
    role: "Owner & Lead Stylist",
    experience: "20+ years",
    origin: "Tokyo, Japan",
    bio: "Kei Hirata is the owner and lead stylist at Three Degrees Salon. Renowned for his meticulous technique and thoughtful approach with 20+ years of experience, Kei is a true all-rounder. Cutting hair since age 13, he trained at the Nihon Beauty Academy and refined his craft at HEAVENS in Harajuku, Tokyo. After working in Vancouver on editorial projects for fashion, TV, and advertising, he moved to New York in 2011 and launched Three Degrees Salon in 2019.",
    specialties: ["Layered Haircut", "Short/Bob Haircut", "Barber's Haircut", "Bleach Process Color", "Balayage/Highlights", "Perm/Digital Perm"],
    photo: "https://threedegreesnyc.com/wp-content/uploads/2023/11/Kei-Hirata_low-res.jpg",
    instagram: "https://www.instagram.com/keihirata_323/",
    bookingUrl: "https://threedegreesnyc.com/appointment/",
    priceRange: "$120 – $150 (Haircut)",
    quote: "He is truly an artist and the work he does is something you can feel confident leaving the salon with.",
  },
  {
    id: "shawn-nakamura",
    name: "Shawn Nakamura",
    role: "Master Stylist",
    experience: "17 years",
    origin: "Kobe, Japan",
    bio: "Shawn Nakamura is a hairstylist with 17 years of experience across four countries — Japan, Amsterdam, Toronto, and New York. Born in Kanagawa and raised in Hyogo, he began his career at a long-established salon in Kobe and Osaka. He joined Three Degrees Salon in July 2021 as a top hairstylist. An expert in edgy shaggy textured designs, his cutting technique for pixie cuts, layered cuts, bobs, and mullets is extraordinary.",
    specialties: ["Shaggy/Textured Haircut", "Pixie Cut", "Layered Cut", "Bob Cut", "Mullet", "Barber's Cut"],
    photo: "https://threedegreesnyc.com/wp-content/uploads/2023/11/Shawn-Nakamura_low-res-1.jpg",
    instagram: "https://www.instagram.com/shaaawn___/",
    bookingUrl: "https://threedegreesnyc.com/appointment/",
    priceRange: "$100 – $130 (Haircut)",
    quote: "He understands hair texture and movement so even 'big' changes to my look feels like it's been that way all along.",
  },
  {
    id: "saeko",
    name: "Saeko",
    role: "Senior Stylist",
    experience: "10+ years",
    origin: "Tokyo, Japan",
    bio: "Saeko grew up in Tokyo and dreamed of becoming a hairstylist from childhood. After graduating from Nihon Beauty Academy, she studied abroad in London before returning to Japan to hone her craft. She moved to NYC in June 2014, serving 7 years at Ridge Salon in East Village before joining Three Degrees Salon in September 2021. Renowned for hair coloring, long/medium layered cuts, and Japanese straightening.",
    specialties: ["Bleach Process Color", "Balayage/Highlights", "Design Colors", "Peekaboo Color", "Long/Medium Layered Haircut", "Japanese Straight Perm"],
    photo: "https://threedegreesnyc.com/wp-content/uploads/2023/11/Saeko_low-res-1.jpg",
    instagram: "https://www.instagram.com/threedegreessalon/",
    bookingUrl: "https://threedegreesnyc.com/appointment/",
    priceRange: "$100 – $130 (Haircut)",
    quote: "Saeko is incredible, definitely go see her if you'd like to get the best hair color and cut of your entire life.",
  },
  {
    id: "yuki-otani",
    name: "Yuki Otani",
    role: "Senior Stylist",
    experience: "10+ years",
    origin: "Tokyo, Japan",
    bio: "Yuki Otani, originally from Tokyo, brings over a decade of expertise to her craft. Inspired by NYC's distinctive style from a young age, she specializes in long layered cuts and colors involving bleaching processes using advanced foiling techniques. She tailors color designs to complement the base cut, clients' hair texture, and volume, excelling in creating shadow and dimension through highlights and balayage.",
    specialties: ["Layered Haircut", "Balayage/Highlights", "Bleach Process Color", "Peekaboo Color", "Short/Bob Haircut", "Perms"],
    photo: "https://threedegreesnyc.com/wp-content/uploads/2023/11/Yuki-Otani.jpg",
    photoFallback: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=533&fit=crop&crop=face",
    instagram: "https://www.instagram.com/threedegreessalon/",
    bookingUrl: "https://threedegreesnyc.com/appointment/",
    priceRange: "$90 – $120 (Haircut)",
    quote: "Yuki is great! She's been coloring and cutting my hair for years and is the only stylist I like.",
  },
  {
    id: "miho-kayanuma",
    name: "Miho Kayanuma",
    role: "Senior Stylist",
    experience: "10+ years",
    origin: "Yamanashi, Japan",
    bio: "Hailing from Yamanashi Prefecture, Miho discovered her passion for hairstyling in high school. She trained at the International Culture and Beauty School and honed her skills at a prestigious salon in Aoyama, Tokyo. Moving to the US in 2013, she returned to Japan in 2018 to refine her skills in salon work, makeup, updos, kimono dressing, and bridal services — earning runner-up in a haircutting contest and the Yamanashi Prefecture Kimono Dressing Competition.",
    specialties: ["Short/Bob Haircut", "Cold Perm/Digital Perm", "Japanese Straightening", "Keratin Treatment", "Updo Styling", "Bridal Updos", "Kimono Dressing"],
    photo: "https://threedegreesnyc.com/wp-content/uploads/2024/01/IMG_0955.jpg",
    photoFallback: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&h=533&fit=crop&crop=face",
    instagram: "https://www.instagram.com/threedegreessalon/",
    bookingUrl: "https://threedegreesnyc.com/appointment/",
    priceRange: "$90 – $120 (Haircut)",
    quote: "Genuinely my favorite salon experience I've had in NYC! Miho was so kind, gentle and detailed.",
  },
  {
    id: "ab-satasak",
    name: "Ab Satasak",
    role: "Stylist",
    experience: "10 years",
    origin: "Bangkok, Thailand",
    bio: "Ab Satasak, originally from Thailand, has been in the hair design industry for 10 years. Before becoming a hairstylist, he worked as an architect for five years — a background that deeply influences his approach to hair as structure, line, and movement. He worked at a well-known barber in Bangkok before moving to New York to expand his creativity. His personal mantra: 'Send them home happy.'",
    specialties: ["Shoulder-Length Haircut", "Short Haircut", "Layered Bob", "Pixie Haircut", "Men's Haircut"],
    photo: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Ab-Profile-Image-1.jpg",
    photoFallback: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=533&fit=crop&crop=face",
    instagram: "https://www.instagram.com/o.double.ff/",
    bookingUrl: "https://threedegreesnyc.com/appointment/",
    priceRange: "$70 – $90 (Haircut)",
    quote: "He was incredibly gentle even when brushing, and so kind throughout. One of the best haircuts I've ever had.",
  },
  {
    id: "savannah-renee",
    name: "Savannah Renee",
    role: "Stylist",
    experience: "4+ years",
    origin: "El Paso, Texas",
    bio: "Originally from El Paso, Texas, Savannah has been passionate about hair since childhood. After four years behind the chair, she moved to New York City to grow her craft. Her approach, influenced by Japanese cutting and coloring techniques, emphasizes precision, intention, and a refined sense of shape and flow. Her style is youthful, detailed, and trend-conscious, balancing softness with a subtle edge.",
    specialties: ["Hush Haircut", "Wolf Haircut", "Modern Layered Haircut", "Bleach Process Color", "Balayage/Highlights", "Design Colors"],
    photo: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Savannah.jpg",
    photoFallback: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=533&fit=crop&crop=face",
    instagram: "https://www.instagram.com/threedegreessalon/",
    bookingUrl: "https://threedegreesnyc.com/appointment/",
    priceRange: "$90 – $120 (Haircut)",
    quote: "Savannah is literally the best hair stylist ever. I'm so happy I found her — she always nails exactly what I want.",
  },
];

export const SERVICES = [
  {
    id: "haircut",
    name: "Haircut",
    tagline: "Precision cuts for every hair type",
    description: "No matter your hair type, our professional stylists have mastered every texture — from thick straight to wavy fine hair. You'll leave not only with a big smile but feeling the difference in how your hair looks, styles, and grows.",
    icon: "✂️",
    image: "/manus-storage/hero-stylist.png",
    startingPrice: "$70",
    duration: "60–90 min",
    includes: ["Consultation", "Shampoo & Blow-dry included"],
    pricing: [
      { item: "Haircut with Kei", price: "$120 – $150" },
      { item: "Haircut with Shawn / Saeko", price: "$100 – $130" },
      { item: "Haircut with Yuki / Miho / Savannah", price: "$90 – $120" },
      { item: "Haircut with Ab", price: "$70 – $90" },
      { item: "Bang / Neck Trim", price: "$30+" },
    ],
    note: "Shampoo & Blow-dry included in all haircut services except Bang/Neck Trim.",
  },
  {
    id: "color",
    name: "Color",
    tagline: "Tailored color for your unique hair",
    description: "We work with multiple professional bleaching and coloring brands, carefully selected to match each client's specific needs. Through a thorough assessment of your hair condition and color goals, we deliver beautiful results while keeping damage to a minimum.",
    icon: "🎨",
    image: "/manus-storage/hero-color.png",
    startingPrice: "$145",
    duration: "2–5 hours",
    includes: ["Consultation", "Color assessment", "Blow-dry"],
    pricing: [
      { item: "Single Color Touch-Up", price: "$145 – $155" },
      { item: "Single Color Full Head", price: "$160 – $190" },
      { item: "Single Color + Haircut (Touch-Up)", price: "$210 – $230" },
      { item: "Single Color + Haircut (Full Head)", price: "$240 – $280" },
      { item: "Double Color Process", price: "$290 – $350" },
      { item: "Bleach Single Process", price: "$300 – $400" },
      { item: "Bleach Double Process", price: "$450 – $600" },
      { item: "Full Highlights / Balayage", price: "$330 – $480" },
      { item: "Highlights / Balayage Touch-Up", price: "$290 – $350" },
      { item: "Peekaboo / Point Color", price: "$290 – $390" },
      { item: "Creative / Color Correction", price: "$700+ (Consultation required)" },
    ],
    note: "Price depends on hair length and stylist. Email for online consultation before booking color correction.",
  },
  {
    id: "perm",
    name: "Perm & Straightening",
    tagline: "Japanese technique, lasting results",
    description: "Aiming for wet, beachy waves, a natural soft wavy hairstyle, or simply adding volume? Our perming technique is designed to help you achieve exactly that. We use Japanese tools to ensure exceptional results.",
    icon: "〰️",
    image: "/manus-storage/hero-main.png",
    startingPrice: "$280",
    duration: "3–5 hours",
    includes: ["Consultation", "Haircut included with perm"],
    pricing: [
      { item: "Perm with Haircut (Kei)", price: "$320 – $400" },
      { item: "Digital Perm with Haircut (Kei)", price: "$320 – $400" },
      { item: "Perm / Digital Perm (Yuki / Miho / Shawn / Saeko)", price: "$280 – $350" },
      { item: "Japanese Straightening", price: "$330 – $380" },
      { item: "Keratin Treatment", price: "$350 – $400" },
    ],
    note: "Haircut included with all perm services. Clients with bleached hair are not eligible for perm services.",
  },
  {
    id: "styling",
    name: "Styling",
    tagline: "For your special day and every day",
    description: "Whether it's your wedding day or just a day to feel beautiful, our styling services have you covered. Each Shampoo & Blow-Dry includes a relaxing wash followed by a customized finish using brushes, heated rollers, and irons.",
    icon: "💫",
    image: "/manus-storage/salon-interior.png",
    startingPrice: "$60",
    duration: "45–90 min",
    includes: ["Shampoo", "Blow-dry", "Style consultation"],
    pricing: [
      { item: "Blow-dry with Shampoo", price: "$60+" },
      { item: "Updo Styling", price: "$130+" },
    ],
    note: "Advanced consultation required for updo styling. Email for weddings, photoshoots, and special events.",
  },
  {
    id: "treatment",
    name: "Treatments",
    tagline: "Restore and strengthen your hair",
    description: "Our Deep Conditioner, powered by innovative Dual-Repair Technology, works wonders for severely damaged and over-processed hair. It rebuilds and strengthens, offering impressive results that last up to 5 weeks, with a home care treatment included.",
    icon: "✨",
    image: "/manus-storage/hero-color.png",
    startingPrice: "$60",
    duration: "30–60 min",
    includes: ["Hair assessment", "Home care kit (Deep Conditioner)"],
    pricing: [
      { item: "OLAPLEX or Deep Conditioner (Standalone)", price: "$110 – $140" },
      { item: "Add-On: OLAPLEX or Deep Conditioner", price: "$60 – $100" },
    ],
    note: "Add-on pricing only available when booked with another service.",
  },
];

export const REVIEWS = [
  {
    id: 1,
    name: "Kristin",
    rating: 5,
    date: "2024-03-15",
    text: "I got a digital perm and olaplex treatment today with Yuki and am super happy with the results! She did an amazing job and was very nice and communicated and we took some time at the beginning to really talk about what I wanted which I appreciated. She was very detail oriented and kept checking in with me throughout the appointment to make sure I was doing okay. There were lots of people there getting perms, so you can really tell that they know their stuff and are well trusted. I actually found this salon when researching digital perms and I saw their informational articles on them. All the employees seemed well trained and very knowledgeable. I highly recommend this place and plan to go back in a few months.",
    service: "Perm",
    stylist: "Yuki",
    source: "Google",
  },
  {
    id: 2,
    name: "Catherine Shi",
    rating: 5,
    date: "2022-05-10",
    text: "I received a cut and digital perm from Kei last week and I had an amazing experience! It was my first time getting a perm so he patiently answered all of my questions and explained each step of the process so I felt very comfortable. I felt like he really took his time to make sure I had a great result which I really appreciate. My hair looks (and feels) amazing and I get so many compliments! Everyone is really nice and their studio is clean and beautiful. I've never had a stylist I loved enough to be a loyal customer but I will definitely be back for Kei! Would highly recommend.",
    service: "Perm",
    stylist: "Kei",
    source: "Google",
  },
  {
    id: 3,
    name: "Erica Pena",
    rating: 5,
    date: "2023-10-27",
    text: "I went in today for a cut with balayage my hair was literally 2 different colors but Saeko did an amazing job. 1st she did a hair consultation, then we looked at what I wanted and the best possible options. Every decision was made by me with her suggestions for the best look. My hair looks amazing. I love the color and cut and I will definitely be back again.",
    service: "Color",
    stylist: "Saeko",
    source: "Google",
  },
  {
    id: 4,
    name: "Kenny House",
    rating: 5,
    date: "2022-05-01",
    text: "Best experience I've ever had with a hair service! I was nervous about what to ask for since I'm not used to getting haircuts with longer hair. I grabbed a variety of pics I use for my own inspiration and Shawn was able to understand my vision and contribute his own expertise and experience and really get something personal to me. He asked about my own routine (products, styling, drying, etc) and was happy to give suggestions and advice. Can't overstate how pleased I am with the experience and will 100% be back in the future!",
    service: "Haircut",
    stylist: "Shawn",
    source: "Google",
  },
  {
    id: 5,
    name: "Sarah Moon",
    rating: 5,
    date: "2023-09-15",
    text: "Haircut & Digital Perm with Kei: Such an amazing experience starting off with a hair consult where Kei really listened and asked a lot of good questions. I trusted his guidance and recommendations for what type of cut would be best for me completely and it paid off. The service and attention to detail throughout my entire appointment was top notch and I'm thrilled with my results of my digital perm! I've been getting them for about 15 years at different salons and Three Degrees has definitely been my favorite. They've found a new customer for life!",
    service: "Perm",
    stylist: "Kei",
    source: "Google",
  },
  {
    id: 6,
    name: "Mike Glaser",
    rating: 5,
    date: "2023-10-22",
    text: "Love Three Degrees, awesome location great cuts, I see Kei, he is the BEST, all hair styles, really adapts hair to your lifestyle and season. Cleanest Cut in East Village, good sound system too.",
    service: "Haircut",
    stylist: "Kei",
    source: "Google",
  },
  {
    id: 7,
    name: "Melanie Tosik",
    rating: 5,
    date: "2023-09-15",
    text: "My favorite place in the world! Saeko is incredible, definitely go see her if you'd like to get the best hair color and cut of your entire life.",
    service: "Color",
    stylist: "Saeko",
    source: "Google",
  },
  {
    id: 8,
    name: "Steve Mazzamuto",
    rating: 5,
    date: "2023-09-30",
    text: "Walked in with a freakin picture of a mullet from a character from a Korean webtoon of all things. Shawn looked at it once and gave me EXACTLY what I wanted. I've gotten nothing but compliments since. I could not recommend him, or this salon more. Extremely professional staff, and they really care to make sure you leave happy.",
    service: "Haircut",
    stylist: "Shawn",
    source: "Google",
  },
  {
    id: 9,
    name: "Christina W",
    rating: 5,
    date: "2023-08-22",
    text: "I am extremely happy about my full highlight/balayage service with Megumu. I have always wanted a subtle muted brown balayage but all the other salons I have been to so far either makes it too light or orange. After I booked the appointment online, Megumu emailed me and asked about my history, and inspirational pictures. There was also an in person consultation at the time of the appointment. The service took about 4 hours but it was well worth it. Megumu was focused, attentive, knowledgeable and detail oriented, which reflects on her work. I can not wait to visit again for my next appointment.",
    service: "Highlights",
    stylist: "Megumu",
    source: "Google",
  },
  {
    id: 10,
    name: "Alex Rickard",
    rating: 5,
    date: "2022-08-15",
    text: "Kei and his staff at Three Degrees Salon are wonderful, friendly, welcoming, easy to chat with, and most importantly — they do an incredible job. I love how they start off with a shampoo and relaxing scalp and temple massage and then offer some green tea. Kei does a great job with my hair and I'm so glad I found him because I won't be going to anyone else anymore. Check them out!",
    service: "Haircut",
    stylist: "Kei",
    source: "Google",
  },
  {
    id: 11,
    name: "Amy Ro",
    rating: 5,
    date: "2022-08-11",
    text: "If you're looking for a salon that always gets it right, look no further. Yes, it's a bit more than most, but I promise it's worth it. Cuts, color, styling... you name it. The sheer meticulous nature of everyone that's here is very impressive. I HIGHLY recommend. To top it off, they're incredibly friendly and super client/customer-focused. They hit every area in an A++ manner and more.",
    service: "Styling",
    stylist: "Team",
    source: "Google",
  },
  {
    id: 12,
    name: "C Y",
    rating: 5,
    date: "2022-06-18",
    text: "Had my hair cut with Kei today. No need to mention that he is incredibly great! I also like the atmosphere of their salon, very clean and organized. If you are someone like me that have a concern with towels used in salon, you will appreciate that they use disposable towels instead. Highly recommend.",
    service: "Haircut",
    stylist: "Kei",
    source: "Google",
  },
  {
    id: 13,
    name: "Grace",
    rating: 5,
    date: "2022-03-06",
    text: "An unassuming but positively amazing hair salon. The vibe is super chill and the hair stylists all seem to have amazing rapport with their clients. Megumu gave me another fantastic cut — she instinctively knew what I wanted and would work best for me. Professional, clean, reasonable pricing and super accommodating. Highly recommend.",
    service: "Haircut",
    stylist: "Megumu",
    source: "Google",
  },
  {
    id: 14,
    name: "Ellie Hueneke",
    rating: 5,
    date: "2023-07-07",
    text: "Saeko did an amazing job transforming my hair! I wanted to get a pixie haircut for the first time and she made me feel confident in such a big change. I would definitely recommend trying this place out if you're in need of an 'on trend' new hairstyle.",
    service: "Haircut",
    stylist: "Saeko",
    source: "Google",
  },
  {
    id: 15,
    name: "Shiela Royama",
    rating: 5,
    date: "2023-08-11",
    text: "Fantastic haircut with Megumu! She has great attention to details and asks for feedback during the process. Gives great mini head massages too. I try to make regular visits to Three Degrees when I'm back in NY and have never regretted an appointment. Looking forward to when I return!",
    service: "Haircut",
    stylist: "Megumu",
    source: "Google",
  },
  {
    id: 16,
    name: "Rajani Tewari",
    rating: 5,
    date: "2023-10-31",
    text: "Highly recommend Three Degrees — had wonderful blowout for a special occasion — a smooth experience!",
    service: "Styling",
    stylist: "Team",
    source: "Google",
  },
  {
    id: 17,
    name: "Lauren Maguire",
    rating: 5,
    date: "2023-10-15",
    text: "Mariko is amazing!! She did exactly what I wanted and gave me really good advice on how to look after my hair type. Amazing Salon!!",
    service: "Haircut",
    stylist: "Mariko",
    source: "Google",
  },
  {
    id: 18,
    name: "connie jan",
    rating: 5,
    date: "2023-08-06",
    text: "I highly recommend Mariko! She's incredibly detail-oriented, gave me exactly the color I wanted, and has a wealth of experience working with wavy hair.",
    service: "Color",
    stylist: "Mariko",
    source: "Google",
  },
  {
    id: 19,
    name: "nicole g",
    rating: 5,
    date: "2023-08-06",
    text: "I got a haircut to treat myself for my birthday and Shawn did an amazing job!! I absolutely loved how it turned out — thank you Shawn for making me look this good on my special day!",
    service: "Haircut",
    stylist: "Shawn",
    source: "Google",
  },
  {
    id: 20,
    name: "y.ahl",
    rating: 5,
    date: "2023-05-26",
    text: "Bleach single process with Saeko turned out so well! I went in with ideas but not having decided on color, but after talking through with Saeko on what I like, she knew exactly how to accommodate. She was thorough and attentive, and I'm very pleased with the color.",
    service: "Color",
    stylist: "Saeko",
    source: "Google",
  },
  {
    id: 21,
    name: "Eva Li",
    rating: 5,
    date: "2023-04-09",
    text: "I had the best haircut with Mariko! She totally understood what I wanted and is clearly an expert in her craft. Swift, precise and gentle. I will be back.",
    service: "Haircut",
    stylist: "Mariko",
    source: "Google",
  },
  {
    id: 22,
    name: "Andy B",
    rating: 5,
    date: "2023-09-08",
    text: "I tried a few other salons until finally going with this one. I've been coming regularly for a little over a year now and Shawn has been great. Calm space, easy bookings (and cancellations), everyone's nice, no complaints.",
    service: "Haircut",
    stylist: "Shawn",
    source: "Google",
  },
  {
    id: 23,
    name: "Deynira Orr",
    rating: 5,
    date: "2023-09-03",
    text: "My second time going to see Shawn and he did an amazing job! My hair always feels and looks 100x better after my appointment.",
    service: "Haircut",
    stylist: "Shawn",
    source: "Google",
  },
  {
    id: 24,
    name: "Rachel Russell",
    rating: 5,
    date: "2021-05-10",
    text: "Saeko is a great stylist and lovely person. She has helped me change hairstyles and I always walk out happy with my cut. The salon is peaceful and the staff people are all friendly.",
    service: "Haircut",
    stylist: "Saeko",
    source: "Google",
  },
  {
    id: 25,
    name: "William Petroni",
    rating: 5,
    date: "2021-06-15",
    text: "Saeko has been cutting my hair for about 2 years now. She recently moved to this lovely peaceful professional salon! It is exactly what you want out of a small neighborhood salon; PERSONAL, kind and efficient service and a friendly atmosphere.",
    service: "Haircut",
    stylist: "Saeko",
    source: "Google",
  },
  {
    id: 26,
    name: "Nadina Bolton-heaton",
    rating: 5,
    date: "2021-08-20",
    text: "I always have a wonderful experience at Three Degrees, and I have been a client for over a year and a half now after moving to NYC in late 2019. The team has incredible attention to detail, true creativity and a genuine desire to make clients look and feel their best.",
    service: "Haircut",
    stylist: "Team",
    source: "Google",
  },
  {
    id: 27,
    name: "Christine D",
    rating: 5,
    date: "2021-09-05",
    text: "This is the first time I visit 3 Degrees and I'm so glad that I chose Kei for my hair cut and single color. I showed a picture with my idea to Kei and not only the color achieves my desire but it is even better than the picture.",
    service: "Color",
    stylist: "Kei",
    source: "Google",
  },
  {
    id: 28,
    name: "Camille Warmington",
    rating: 5,
    date: "2021-07-10",
    text: "Highly recommend Three Degrees Salon. Kei and team are true creatives when it comes to hair of all kinds — highly professional. The salon has an easy online booking system and the fees are very reasonable for the quality of service.",
    service: "Haircut",
    stylist: "Kei",
    source: "Google",
  },
  {
    id: 29,
    name: "Frances McClain",
    rating: 5,
    date: "2021-10-15",
    text: "Never leave Google reviews, but just needed to shout out Three Degrees. I've gotten so many haircuts that have been bad AND expensive in NYC, but this one was excellent, and less than I've paid elsewhere. My hair was in a sorry state when I came in — I'm in the midst of a rough grow-out process — but Shawn still did an amazing job at giving me just the shape I wanted. He was very thorough and attentive.",
    service: "Haircut",
    stylist: "Shawn",
    source: "Google",
  },
  {
    id: 30,
    name: "Joan Wong",
    rating: 5,
    date: "2021-11-20",
    text: "I always walk out of my appointments with Saeko feeling great. She is attentive and patient and so good at what she does. I've also gotten treatment from Kei in the past who is equally lovely.",
    service: "Haircut",
    stylist: "Saeko",
    source: "Google",
  },
  {
    id: 31,
    name: "Caroline Jordan",
    rating: 5,
    date: "2024-01-15",
    text: "Genuinely my favorite salon experience I've had in NYC! Miho was so kind, gentle and detailed. I asked for curtain bangs and layers and I'm so so happy with it! A very calming and attentive experience, I'll definitely be back.",
    service: "Haircut",
    stylist: "Miho",
    source: "Google",
  },
  {
    id: 32,
    name: "Enrique Yaveh",
    rating: 5,
    date: "2024-02-10",
    text: "I visited the salon as a walk-in, and they welcomed me warmly and accommodated me right away. The entire team is fantastic and provide top-notch service, but I had the pleasure of being treated by Miho Kayanuma, who is phenomenal! Miho is incredibly skilled, gentle, and friendly, making the experience truly exceptional. This salon is definitely worth a visit — I'll be coming back to NY just to get my hair cut here!",
    service: "Haircut",
    stylist: "Miho",
    source: "Google",
  },
  {
    id: 33,
    name: "Shennon Lu",
    rating: 5,
    date: "2024-03-20",
    text: "I had a haircut and digital perm with Miho. I'm so happy with the result. It's always an act of trust to place your hair in someone's hands, and Miho really delivered. She did a very precise and meticulous cut that took out the weight, leaving my hair light and airy. The digital perm gave me loose natural waves as I requested. I'm low-key with my hair, and Miho respected this and gave me the natural look I wanted.",
    service: "Perm",
    stylist: "Miho",
    source: "Google",
  },
  {
    id: 34,
    name: "Leticia Souza",
    rating: 5,
    date: "2024-04-05",
    text: "Ab was so nice and really took the time to look closely at my hair, giving me great ideas for more volume. He was incredibly gentle even when brushing, and so kind throughout. He made my hair look so much healthier without cutting too much, and the result is honestly one of the best haircuts I've ever had. My hair feels lighter, shinier, and styled in a way that works for me. Ab is not only very skilled but also genuinely kind. I left the salon feeling confident and so happy with my hair. Highly recommend!",
    service: "Haircut",
    stylist: "Ab",
    source: "Google",
  },
  {
    id: 35,
    name: "Adam Brodnax",
    rating: 5,
    date: "2024-05-12",
    text: "Ab is a great stylist! I have started to grow my hair out the past couple of years and he's helped guide it to the shape I've been wanting. He's super attentive with his scissor cuts and very knowledgeable on what works best! He makes the process very easy and is quite personable + he gives a great hair wash and massage (such a nice add!)",
    service: "Haircut",
    stylist: "Ab",
    source: "Google",
  },
  {
    id: 36,
    name: "Felicia Tersan",
    rating: 5,
    date: "2023-11-10",
    text: "I had a haircut and deep conditioning at Three Degrees, both done by Saeko. Saeko did a fantastic job at cutting my hair. I was unsure about whether the style I wanted would fit me, and she spent time to listen to my concerns and discussed what would look best on me. I appreciate the fact that she didn't rush me through the discussion process despite me being her last client for the day. Saeko's customer service is top notch! Her work is amazing too — she was very detailed and would walk me through her steps. She also gave me some tips on hair care and hair styling. Oh and she gives AMAZING head massages. The deep conditioning treatment is really worth it too — my hair was given four treatment layers which made my hair feel finally normal again.",
    service: "Haircut",
    stylist: "Saeko",
    source: "Google",
  },
  {
    id: 37,
    name: "Claude Wang",
    rating: 5,
    date: "2023-07-20",
    text: "I got a perm with Saeko this July after eyeing the Instagram page for quite a long time! Saeko helped me to choose the appropriate style and was super patient throughout. I loved how it turned out! I highly recommend Three Degrees Salon and will be coming here to get my perms from now on.",
    service: "Perm",
    stylist: "Saeko",
    source: "Google",
  },
  {
    id: 38,
    name: "Ally Policarpio",
    rating: 5,
    date: "2024-06-15",
    text: "Lovely place, very quiet when I went and a relaxing vibe. Yuki was so kind! Has a very light touch and very meticulous with my hair cut. I asked for her honest opinion on whether a certain cut would suit me, and we ultimately went with a compromise given the texture of my hair, and how much styling it would take to maintain on my own. I'll be returning here for sure.",
    service: "Haircut",
    stylist: "Yuki",
    source: "Google",
  },
  {
    id: 39,
    name: "Ana Lai",
    rating: 5,
    date: "2024-07-10",
    text: "Yuki is great! She's been coloring and cutting my hair for years and is the only stylist I like. Love the way she cuts my hair for volume and the highlights look great. Would definitely recommend 3 Degrees and Yuki.",
    service: "Highlights",
    stylist: "Yuki",
    source: "Google",
  },
  {
    id: 40,
    name: "Eva B",
    rating: 5,
    date: "2023-12-05",
    text: "Followed Saeko with my husband for her expertise in cut and color fabulous for both men and women to this new Salon opened by Kei who did a really nice layered cut for my husband's hair on a previous occasion. I can always trust Saeko to be nice and listen to my needs and give good recommendations for products and style.",
    service: "Color",
    stylist: "Saeko",
    source: "Yelp",
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    title: "The Essential Guide to Digital Perm & Hottest 7 Styles for Every Length",
    slug: "digital-perm-guide",
    category: "Perm",
    date: "2025-08-04",
    excerpt: "Everything you need to know about digital perms — from the science behind the technique to the hottest styles for short, medium, and long hair.",
    image: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Digital-Perm.png",
    url: "https://threedegreesnyc.com/the-essential-guide-to-digital-perm-hottest-7-styles-for-every-length/",
  },
  {
    id: 2,
    title: "10 Trending Bridal Hairstyles Loved by Wedding Hair Experts",
    slug: "bridal-hairstyles",
    category: "Styling",
    date: "2025-05-01",
    excerpt: "From romantic updos to flowing waves, discover the bridal hairstyles that are captivating brides and stylists alike this season.",
    image: "https://threedegreesnyc.com/wp-content/uploads/2024/08/IMG_9474.jpg",
    url: "https://threedegreesnyc.com/10-trending-bridal-hairstyles-loved-by-wedding-hair-experts/",
  },
  {
    id: 3,
    title: "31 Celebrity-Inspired Layered Hairstyles New Yorkers Love",
    slug: "layered-hairstyles",
    category: "Haircut",
    date: "2025-03-12",
    excerpt: "The layered haircut is having a major moment. Here are 31 celebrity-inspired looks that our NYC clients are requesting most.",
    image: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Shaggy-Layered-Haircut.jpg",
    url: "https://threedegreesnyc.com/31-celebrity-inspired-layered-hairstyles/",
  },
  {
    id: 4,
    title: "First Time Perm Guide: Choosing & Ordering the Perfect Perm",
    slug: "first-time-perm",
    category: "Perm",
    date: "2024-12-12",
    excerpt: "Getting your first perm? This comprehensive guide walks you through everything — from choosing the right type to what to expect during your appointment.",
    image: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Perm.jpg",
    url: "https://threedegreesnyc.com/first-time-perm-guide/",
  },
  {
    id: 5,
    title: "The Ultimate Guide: Japanese Straightening vs Keratin Treatment",
    slug: "straightening-vs-keratin",
    category: "Straightening",
    date: "2024-06-15",
    excerpt: "Two of the most popular smoothing treatments, but which one is right for you? We break down the differences, results, and aftercare for both.",
    image: "https://threedegreesnyc.com/wp-content/uploads/2024/08/Keratin-Treatment.jpg",
    url: "https://threedegreesnyc.com/the-ultimate-guide-japanese-straightening-vs-keratin-treatment/",
  },
  {
    id: 6,
    title: "34 Iconic Short Haircuts that Suit Your Face Shape",
    slug: "short-haircuts",
    category: "Haircut",
    date: "2024-01-13",
    excerpt: "The right short haircut can transform your entire look. Here are 34 iconic styles matched to every face shape.",
    image: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Subtle-Angle-Bob.jpg",
    url: "https://threedegreesnyc.com/34-iconic-short-haircuts-that-suit-your-face-shape/",
  },
  {
    id: 7,
    title: "Balayage 101: The Basics to Know and 8 Elegant Balayage Colors",
    slug: "balayage-guide",
    category: "Color",
    date: "2023-03-14",
    excerpt: "Balayage remains one of the most requested color techniques at our salon. Here's everything you need to know before booking.",
    image: "https://threedegreesnyc.com/wp-content/uploads/2023/10/Caramel-Balayage.jpg",
    url: "https://threedegreesnyc.com/balayage101_basics_to_know_and_8_elegant_colors/",
  },
  {
    id: 8,
    title: "Hair Color Guide: How to Choose the Right Menu for You",
    slug: "hair-color-guide",
    category: "Color",
    date: "2022-07-30",
    excerpt: "Not sure which color service to book? This guide breaks down every option — from single process to bleach and beyond — so you can arrive with confidence.",
    image: "https://threedegreesnyc.com/wp-content/uploads/2024/08/Double-Process-Color.jpg",
    url: "https://threedegreesnyc.com/haircolorguide_forbooking/",
  },
];

export const FAQS = [
  {
    category: "Appointments",
    questions: [
      {
        q: "Do I need an appointment?",
        a: "Appointments are strongly recommended as our stylists book up quickly. Walk-ins are accepted based on availability, but we cannot guarantee a specific stylist or service without a booking.",
      },
      {
        q: "How do I book an appointment?",
        a: "You can book online through our booking system at threedegreesnyc.com/appointment, or call us at (212) 254-8174. For color corrections or special events, please email us at info@threedegreesnyc.com first for a consultation.",
      },
      {
        q: "What is your cancellation policy?",
        a: "We ask that you cancel or reschedule at least 24 hours in advance. Late cancellations or no-shows may be subject to a fee.",
      },
      {
        q: "What if I'm running late?",
        a: "Please notify us as soon as possible if you're running late. Depending on the service and our schedule, we may need to adjust your appointment or reschedule.",
      },
    ],
  },
  {
    category: "Hair Color",
    questions: [
      {
        q: "Do I need a consultation before a color appointment?",
        a: "For standard color services, a consultation happens at the start of your appointment. For color corrections, creative colors, or if you've had box dye, we strongly recommend emailing us at info@threedegreesnyc.com with photos of your current hair and desired look before booking.",
      },
      {
        q: "Can I get a perm if I've had bleach?",
        a: "No. We do not offer perm services on hair that has been bleached. Bleached hair is too fragile for the chemical process involved in perming.",
      },
      {
        q: "How long does a color service take?",
        a: "Color services typically take 2–5 hours depending on the service. Full highlights or balayage can take 3–4 hours. Color corrections may take longer.",
      },
      {
        q: "What brands do you use for color?",
        a: "We work with multiple professional bleaching and coloring brands, carefully selected to match each client's specific needs and hair type.",
      },
    ],
  },
  {
    category: "Pricing",
    questions: [
      {
        q: "Why do prices vary by stylist?",
        a: "Our pricing reflects each stylist's level of experience and expertise. Senior stylists with more years of experience are priced higher. All our stylists are highly skilled — the difference is in their specialization and tenure.",
      },
      {
        q: "Are shampoo and blow-dry included?",
        a: "Yes — shampoo and blow-dry are included with all haircut services except Bang/Neck Trim.",
      },
      {
        q: "What payment methods do you accept?",
        a: "We accept all major credit cards, debit cards, and NFC payments (Apple Pay, Google Pay).",
      },
    ],
  },
  {
    category: "Treatments",
    questions: [
      {
        q: "What is the difference between OLAPLEX and Deep Conditioner?",
        a: "OLAPLEX uses Bond Building technology to repair damaged hair from within — ideal for bleached or chemically treated hair. Our Deep Conditioner is a 4-step treatment for severely damaged hair that lasts up to 5 weeks and includes a home care kit.",
      },
      {
        q: "What is Japanese Straightening?",
        a: "Japanese Straightening (also called thermal reconditioning) permanently straightens hair using a Japanese chemical process followed by heat. Results are pin-straight and last until new growth appears.",
      },
      {
        q: "What is the difference between a Digital Perm and a Cold Perm?",
        a: "A Digital Perm uses heat rods to create soft, bouncy waves that look best when dry. A Cold Perm uses room-temperature chemicals to create tighter, springier curls that look best when wet. Our stylists can recommend the best option for your hair type and desired style.",
      },
    ],
  },
  {
    category: "Accessibility",
    questions: [
      {
        q: "Is the salon wheelchair accessible?",
        a: "Yes — we have a wheelchair-accessible entrance and wheelchair seating available.",
      },
      {
        q: "Do you have a gender-neutral restroom?",
        a: "Yes, we have a gender-neutral restroom available for all clients.",
      },
      {
        q: "Do you offer complimentary beverages?",
        a: "Yes — we offer complimentary beverages including green tea during your appointment.",
      },
    ],
  },
];

export const GALLERY_IMAGES = [
  // Haircuts
  { id: 1, url: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Medium-Textured-Cut.jpg", category: "Haircuts", alt: "Medium Textured Cut", stylist: "Kei" },
  { id: 2, url: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Shaggy-Layered-Haircut.jpg", category: "Haircuts", alt: "Shaggy Layered Haircut", stylist: "Kei" },
  { id: 3, url: "https://threedegreesnyc.com/wp-content/uploads/2023/10/Shag-Mullet-Haircut-2.jpg", category: "Haircuts", alt: "Shag Mullet Haircut", stylist: "Kei" },
  { id: 4, url: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Subtle-Angle-Bob.jpg", category: "Haircuts", alt: "Subtle Angle Bob", stylist: "Saeko" },
  { id: 5, url: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Wavy-Haircut.jpg", category: "Haircuts", alt: "Wavy Haircut", stylist: "Saeko" },
  { id: 6, url: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Layered-Haircut.jpg", category: "Haircuts", alt: "Layered Haircut", stylist: "Saeko" },
  { id: 7, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/Medium-Haircut-with-Layers.jpg", category: "Haircuts", alt: "Medium Haircut with Layers", stylist: "Yuki" },
  { id: 8, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/Bob-Haircut.jpg", category: "Haircuts", alt: "Bob Haircut", stylist: "Yuki" },
  { id: 9, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Short-Haircut-2.jpg", category: "Haircuts", alt: "Short Haircut", stylist: "Ab" },
  { id: 10, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Short-Haircut.jpg", category: "Haircuts", alt: "Short Haircut", stylist: "Ab" },
  { id: 11, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Shaggy-Bangs-Layered-Cut.jpg", category: "Haircuts", alt: "Shaggy Bangs Layered Cut", stylist: "Ab" },
  { id: 12, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Medium-Length-Haircut.jpg", category: "Haircuts", alt: "Medium Length Haircut", stylist: "Ab" },
  { id: 13, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Curtain-Bangs.jpg", category: "Haircuts", alt: "Curtain Bangs", stylist: "Miho" },
  { id: 14, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Haircut-for-curly-hair.jpg", category: "Haircuts", alt: "Haircut for Curly Hair", stylist: "Miho" },
  // Balayage
  { id: 15, url: "https://threedegreesnyc.com/wp-content/uploads/2023/10/Balayage.jpg", category: "Balayage", alt: "Balayage", stylist: "Kei" },
  { id: 16, url: "https://threedegreesnyc.com/wp-content/uploads/2023/10/Caramel-Balayage.jpg", category: "Balayage", alt: "Caramel Balayage", stylist: "Kei" },
  { id: 17, url: "https://threedegreesnyc.com/wp-content/uploads/2023/10/Caramel-Balayage-2.jpg", category: "Balayage", alt: "Caramel Balayage", stylist: "Saeko" },
  { id: 18, url: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Golden-Blonde-Balayage.jpg", category: "Balayage", alt: "Golden Blonde Balayage", stylist: "Saeko" },
  { id: 19, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/Highlights.jpg", category: "Highlights", alt: "Highlights", stylist: "Yuki" },
  // Color
  { id: 20, url: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Color-Correction.jpg", category: "Color", alt: "Color Correction", stylist: "Kei" },
  { id: 21, url: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Pink-Highlight.jpg", category: "Color", alt: "Pink Highlight", stylist: "Saeko" },
  { id: 22, url: "https://threedegreesnyc.com/wp-content/uploads/2023/08/Moneypiece-Peekaboo.jpg", category: "Color", alt: "Moneypiece Peekaboo", stylist: "Saeko" },
  { id: 23, url: "https://threedegreesnyc.com/wp-content/uploads/2023/08/Pink-Money-Piece.jpg", category: "Color", alt: "Pink Money Piece", stylist: "Saeko" },
  { id: 24, url: "https://threedegreesnyc.com/wp-content/uploads/2023/08/Purple-Partial-Color.jpg", category: "Color", alt: "Purple Partial Color", stylist: "Saeko" },
  { id: 25, url: "https://threedegreesnyc.com/wp-content/uploads/2023/08/Blonde-Moneypiece-Partial-Color.jpg", category: "Color", alt: "Blonde Moneypiece", stylist: "Saeko" },
  { id: 26, url: "https://threedegreesnyc.com/wp-content/uploads/2023/08/Soft-Blue-Hair.jpg", category: "Color", alt: "Soft Blue Hair", stylist: "Saeko" },
  { id: 27, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/Double-Process-Color.jpg", category: "Color", alt: "Double Process Color", stylist: "Yuki" },
  // Perm
  { id: 28, url: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Digital-Perm.png", category: "Perm", alt: "Digital Perm", stylist: "Kei" },
  { id: 29, url: "https://threedegreesnyc.com/wp-content/uploads/2023/10/Short-Digital-Perm-men-side.jpg", category: "Perm", alt: "Short Digital Perm Men", stylist: "Kei" },
  { id: 30, url: "https://threedegreesnyc.com/wp-content/uploads/2023/10/Shaggy-Soft-Mullet-Digital-Perm.jpg", category: "Perm", alt: "Shaggy Soft Mullet Digital Perm", stylist: "Kei" },
  { id: 31, url: "https://threedegreesnyc.com/wp-content/uploads/2023/10/Long-Layered-S-Carl-Digital-Perm-2.jpg", category: "Perm", alt: "Long Layered Digital Perm", stylist: "Kei" },
  { id: 32, url: "https://threedegreesnyc.com/wp-content/uploads/2023/10/Long-Digital-Perm-2.jpg", category: "Perm", alt: "Long Digital Perm", stylist: "Kei" },
  { id: 33, url: "https://threedegreesnyc.com/wp-content/uploads/2024/01/Perm.jpg", category: "Perm", alt: "Perm", stylist: "Kei" },
  { id: 34, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/Perm-and-Cut.jpg", category: "Perm", alt: "Perm and Cut", stylist: "Yuki" },
  { id: 35, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/Cold-Perm-with-Textured-Haircut.jpg", category: "Perm", alt: "Cold Perm with Textured Haircut", stylist: "Yuki" },
  { id: 36, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Digital-Perm.jpg", category: "Perm", alt: "Digital Perm", stylist: "Miho" },
  { id: 37, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Cold-Perm-1.jpg", category: "Perm", alt: "Cold Perm", stylist: "Miho" },
  { id: 38, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Digital-Perm-Long.jpg", category: "Perm", alt: "Long Digital Perm", stylist: "Miho" },
  // Men
  { id: 39, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Mens-haircut.jpg", category: "Men", alt: "Men's Haircut", stylist: "Ab" },
  { id: 40, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Short-Haircut-3.jpg", category: "Men", alt: "Men's Short Haircut", stylist: "Ab" },
  { id: 41, url: "https://threedegreesnyc.com/wp-content/uploads/2023/10/Short-Digital-Perm-men-side.jpg", category: "Men", alt: "Men's Digital Perm", stylist: "Kei" },
  // Bridal
  { id: 42, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/IMG_9474.jpg", category: "Bridal", alt: "Bridal Updo", stylist: "Miho" },
  { id: 43, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/IMG_6553.jpg", category: "Bridal", alt: "Bridal Hair Back", stylist: "Miho" },
  { id: 44, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/IMG_8672.jpg", category: "Bridal", alt: "Bridal Hair", stylist: "Miho" },
  { id: 45, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/IMG_7831.jpg", category: "Bridal", alt: "Bridal Kimono Hair", stylist: "Miho" },
  { id: 46, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/IMG_9047.jpg", category: "Bridal", alt: "Bridal Kimono Hair", stylist: "Miho" },
  // Keratin / Treatments
  { id: 47, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/Keratin-Treatment.jpg", category: "Treatments", alt: "Keratin Treatment", stylist: "Yuki" },
  { id: 48, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/Back-Perm-and-Cut.jpg", category: "Perm", alt: "Back Perm and Cut", stylist: "Yuki" },
  { id: 49, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Digital-Perm-Back.jpg", category: "Perm", alt: "Digital Perm Back", stylist: "Miho" },
  { id: 50, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Bob-Haircut.jpg", category: "Haircuts", alt: "Bob Haircut", stylist: "Ab" },
  { id: 51, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/One-Length-Cut.jpg", category: "Haircuts", alt: "One Length Cut", stylist: "Ab" },
  { id: 52, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Bang-cut.jpg", category: "Haircuts", alt: "Bang Cut", stylist: "Ab" },
  { id: 53, url: "https://threedegreesnyc.com/wp-content/uploads/2024/10/Haircut-1.jpg", category: "Haircuts", alt: "Haircut", stylist: "Ab" },
  { id: 54, url: "https://threedegreesnyc.com/wp-content/uploads/2024/08/IMG_9234.jpg", category: "Bridal", alt: "Bridal Hair Style", stylist: "Miho" },
];

export const GALLERY_CATEGORIES = ["All", "Haircuts", "Balayage", "Highlights", "Color", "Perm", "Men", "Bridal", "Treatments"];
